// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sueyclwoqdqoemefarur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1ZXljbHdvcWRxb2VtZWZhcnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Mzg2MDcsImV4cCI6MjA2NzMxNDYwN30.VwNlBfiuwMx_VQv8iiabG1URXImTMTXXPG7kgr86Bc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});